/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeletePsswordArgs } from "./DeletePsswordArgs";
import { PsswordCountArgs } from "./PsswordCountArgs";
import { PsswordFindManyArgs } from "./PsswordFindManyArgs";
import { PsswordFindUniqueArgs } from "./PsswordFindUniqueArgs";
import { Pssword } from "./Pssword";
import { PsswordService } from "../pssword.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Pssword)
export class PsswordResolverBase {
  constructor(
    protected readonly service: PsswordService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Pssword",
    action: "read",
    possession: "any",
  })
  async _psswordsMeta(
    @graphql.Args() args: PsswordCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Pssword])
  @nestAccessControl.UseRoles({
    resource: "Pssword",
    action: "read",
    possession: "any",
  })
  async psswords(
    @graphql.Args() args: PsswordFindManyArgs
  ): Promise<Pssword[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Pssword, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Pssword",
    action: "read",
    possession: "own",
  })
  async pssword(
    @graphql.Args() args: PsswordFindUniqueArgs
  ): Promise<Pssword | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Pssword)
  @nestAccessControl.UseRoles({
    resource: "Pssword",
    action: "delete",
    possession: "any",
  })
  async deletePssword(
    @graphql.Args() args: DeletePsswordArgs
  ): Promise<Pssword | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
